ad_campaign_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: /keys/gcp-service-account.json
      project: 
      dataset: 
      location: US
      threads: 4
      timeout_seconds: 300