version: "3.9"

services:
  airflow:
    build: .
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/keys/gcp-service-account.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./dbt:/opt/dbt
      - ./data:/opt/airflow/data
      - ./keys:/opt/airflow/keys:ro
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --role Admin --username admin --email admin@admin.com --firstname admin --lastname admin --password admin || echo 'User already exists' &&
        airflow webserver --port 8080 &
        airflow scheduler
      "
    restart: always
